name: Carga diária Clima

on:
  schedule:
    - cron: '0 11 * * *'  # Roda todo dia às 08h (horário de Brasília)
  workflow_dispatch:      # Permite rodar manualmente também

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: pip install pandas requests

      - name: Executar script de ingestão
        run: python coleta_clima.py

      - name: Salvar CSV como artifact
        uses: actions/upload-artifact@v3
        with:
          name: clima_csv
          path: dados_clima.csv
